spring:
  main.banner-mode: off
  mongodb:
#    uri: mongodb://localhost:27017/staff
    uri: mongodb+srv://vitrivanov:1234@cluster0.t1r3ogk.mongodb.net/staff

server:
  port: 8095
  servlet:
    context-path: /mongo

management:
  #  endpoints.web.exposure.include: 'prometheus, metrics, info, health, env, refresh, beans, mappings'
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      access: read_only
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
