version: '3.8'
services:
  localstack:
    image: localstack/localstack:3.0.2
    container_name: localstack
    ports:
      - 4510-4559:4510-4559
      - 4566:4566
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY=test
      - AWS_SECRET_ACCESS_KET=test
      - DEBUG=${DEBUG:-1}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/aws:/etc/localstack/init/ready.d"