version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
    depends_on:
      - app2
      - db
    ports:
      - '8090:8090'

  app2:
    image: docker.io/colvir/spring-boot:latest
    ports:
      - "8081:8090"

  db-init:
    image: postgres:17.4-alpine
    depends_on:
      - db
    environment:
      - POSTGRES_MULTIPLE_DATABASES=client:client,account:account,processing:processing
      - POSTGRES_USER=colvir
      - POSTGRES_PASSWORD=colvir
      - POSTGRES_HOST=db.db-backend
    volumes:
      - ./config/postgres/entrypoint:/docker-entrypoint-initdb.d
    entrypoint: "/docker-entrypoint-initdb.d/001-create-multiple-postgresql-databases.sh"
    networks:
      db-backend:

  db:
    image: postgres:17.4-alpine
    container_name: postgres_17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
    networks:
      db-backend:
        aliases:
          - db.db-backend

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'

volumes:
  postgres-volume:

networks:
  db-backend: