version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
    depends_on:
      - app2
      - db
    ports:
      - '8090:8090'

  app2:
    image: docker.io/colvir/spring-boot:latest
    ports:
      - "8081:8090"

  db:
    #    platform: linux/x86_64
    image: postgres:17.4-alpine
    container_name: postgres_17
    restart: always
    environment:
      - POSTGRES_DB=colvir
      - POSTGRES_USER=colvir
      - POSTGRES_PASSWORD=colvir
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'

volumes:
  postgres-volume: