### Create client
GET http://localhost:8801/create?name=Vitalii

### Get client info
GET http://localhost:8801/get

### Update client name
GET http://localhost:8801/update/1?name=Vitalii Ivanov

### Get info about client with id 1
GET http://localhost:8801/get/1

### Delete client with id 1
GET http://localhost:8801/delete/1