spring:
  application:
    name: ClientService
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:postgresql://localhost:5432/client
    username: client
    password: client
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: 'classpath:db-migrations/changeLog.xml'

server:
  port: 8801

#spring.datasource:
##  url: jdbc:h2:file:./ClientService;DB_CLOSE_ON_EXIT=FALSE
#  url: jdbc:h2:tcp://localhost:1521/~./ClientService
#  driverClassName: org.h2.Driver
#  username: sa
#  password:

spring.jpa:
  open-in-view: false
#  database-platform: org.hibernate.dialect.H2Dialect
  hibernate.ddl-auto: validate
  generate-ddl: false
#  properties.hibernate.hbm2ddl.auto: update

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

management:
  endpoints.web.exposure.include: 'prometheus, metrics, info, health, env'
  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
