spring:
  application:
    name: ClientService
  main:
    banner-mode: 'off'

server:
  port: 8801

spring.datasource:
  url: jdbc:h2:file:./ClientService;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password:

spring.jpa:
  open-in-view: false
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate.ddl-auto: create-drop
  generate-ddl: true
  properties.hibernate.hbm2ddl.auto: create-drop

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints.web.exposure.include: 'prometheus, metrics, info, health, env'
  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
