cloud.aws:
  region.static: us-east-1
  s3:
    bucket: bucket-s3
    disable-ssl-validation: false
    endpoint: http://localhost:4566/
  credentials:
    access-key: test
    secret-key: test

spring:
  application:
    name: StorageService
  main:
    banner-mode: 'off'

server:
  port: 8809

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

management:
  endpoints.web.exposure.include: 'prometheus, metrics, info, health, env, refresh'
  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
