spring:
  application:
    name: HistoryService
  main:
    banner-mode: 'off'
  config:
    import: optional:configserver:http://localhost:8600
  cloud:
    bus:
      ack:
        enabled: false
      enabled: true

server:
  port: 8807

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

management:
  endpoints.web.exposure.include: 'prometheus, metrics, info, health, env, refresh'
  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
