spring:
  main:
    banner-mode: 'off'
  application:
    name: ApiGateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account_route
              uri: lb://AccountService
              predicates:
                - Path=/account/**
              filters:
                - StripPrefix=1
            - id: client_route
              uri: lb://ClientService
              predicates:
                - Path=/client/**
              filters:
                - StripPrefix=1
            - id: card_route
              uri: lb://CardService
              predicates:
                - Path=/card/**
              filters:
                - StripPrefix=1
            - id: processing_route
              uri: lb://ProcessingService
              predicates:
                - Path=/processing/**
              filters:
                - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 80

management:
  endpoints.web.exposure.include: 'gateway, prometheus, metrics, info, health, env'
  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true