spring:
  application:
    name: CardService
  cloud:
    stream:
      default:
        producer:
          use-native-encoding: true # avoid Base64-encoding of message payload for all producers
      bindings:
        notifications:
          destination: colvir.cards
    bus:
      ack:
        enabled: false
      trace:
        enabled: true
  kafka:
#    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  main:
    banner-mode: 'off'
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8500/realms/example/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8500/realms/example
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway-client
            client-secret: YuxW0c4MKlVcFJFB58JRN7yFFaEIoDdO
            authorization-grant-type: authorization_code
            scope: openid

server:
  port: 8803
#  port: 0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

# can be used random port together with server.port = 0
#  instance:
#    instance-id: ${spring.application.name}:${random.int}

management:
  endpoints.web.exposure.include: 'prometheus, metrics, info, health, env, refresh'
  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1

