spring:
  jms:
    listener:
      min-concurrency: 1
      max-concurrency: 10
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/colvir
    username: colvir
    password: colvir
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  liquibase:
    change-log: 'classpath:db-migrations/changeLog.xml'

app:
  version: 1.0.0
  digit: 123
  jwt:
    secret: theStrongestPasswordAllOverTheWorld
  context:
    file: /spring-context.xml

server:
  port: 8090
  servlet:
    context-path: /app

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.colvir.webinar5
