spring:
  main.banner-mode: off
  datasource:
    name: TEST

app:
  version: 1.0.0
  digit: 123
  context:
    file: /spring-context.xml

server:
  port: 8090
#  servlet:
#    context-path: /app

springdoc:
  swagger-ui:
    use-root-path: true
    path: /swagger-ui.html
  #  api-docs:
  #    path: /api-docs
  packages-to-scan: com.colvir.webinar5
