spring:
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/colvir
    username: colvir
    password: colvir
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true

app:
  version: 1.0.0
  digit: 123
  context:
    file: /spring-context.xml

server:
  port: 8090
  servlet:
    context-path: /app

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.colvir.webinar5
