spring:
  main.banner-mode: off
#  spring.thymeleaf:
#    prefix: 'classpath:/templates/'
#    suffix: '.html'
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN

server:
  port: 8085
  servlet:
    context-path: /web
