spring:
  main.banner-mode: off
#  spring.thymeleaf:
#    prefix: 'classpath:/templates/'
#    suffix: '.html'
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN

server:
  port: 8085
  servlet:
    context-path: /web

management:
  #  endpoints.web.exposure.include: 'prometheus, metrics, info, health, env, refresh, beans, mappings'
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      access: read_only
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
