spring:
  main:
    banner-mode: 'off'
  application:
    name: staff
  data:
    mongodb:
      database: staff
      port: 27017
#      host: localhost
#      uri: mongodb://localhost:27017/library?replicaSet=test&connectTimeoutMS=120000
#      replicaSet=rs0&readPreference=primaryPreferred&retryWrites=false&maxIdleTimeMS=30000

server:
  port: 9090

logging:
  config: classpath:logback.xml

management:
  endpoints.web.exposure.include: 'prometheus, metrics, info, health, env, refresh, beans, mappings'
  endpoint:
    env:
      show-values: always
    health:
      show-details: always
    metrics:
      access: read_only
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
